### ISSUE TITLE
border_radius isn't recognized as a command even though i built the project from source

### ISSUE THREAD

**Issue by dark-eraser** [resloved/i3#15]
I installed i3-gaps a few months ago and at that time couldn't get the `border_radius X` option to work, since the i3 config interpreter didn't seem to recognize the parameter. So today i had the time to recompile the project from source, but still it doesn't work.
Could you maybe tell me what I might be doing wrong ?
The error message i get
```
ERROR: CONFIG: Expected one of these tokens: <end>, '#', 'set ', 'set   ', 'set_from_resource', 'bindsym', 'bindcode', 'bind', 'bar', 'font', 'mode', 'gaps', 'smart_borders', 'smart_gaps', 'floating_minimum_size', 'floating_maximum_size', 'floating_modifier', 'default_orientation', 'workspace_layout', 'default_border', 'new_window', 'default_floating_border', 'new_float', 'hide_edge_borders', 'for_window', 'assign', 'no_focus', 'focus_follows_mouse', 'mouse_warping', 'focus_wrapping', 'force_focus_wrapping', 'force_xinerama', 'force-xinerama', 'disable_randr15', 'disable-randr15', 'workspace_auto_back_and_forth', 'fake_outputs', 'fake-outputs', 'force_display_urgency_hint', 'focus_on_window_activation', 'title_align', 'show_marks', 'workspace', 'ipc_socket', 'ipc-socket', 'ipc_kill_timeout', 'restart_state', 'popup_during_fullscreen', 'exec_always', 'exec', 'client.background', 'client.focused_inactive', 'client.focused', 'client.unfocused', 'client.urgent', 'client.placeholder'
ERROR: CONFIG: (in file /home/darkeraser/.config/i3/config)
ERROR: CONFIG: Line  20: for_window [class=".*"] border pixel 0
ERROR: CONFIG: Line  21: 
ERROR: CONFIG: Line  22: border_radius 6
ERROR: CONFIG:           ^^^^^^^^^^^^^^^
```
Thanks !!

**Comment by resloved** [comment]
Can you share the output of `i3 -v`?

**Comment by dark-eraser** [comment]
`i3 version 4.18-30-gfac60001 (2020-02-24, branch "gaps-next") © 2009 Michael Stapelberg and contributors`

**Comment by resloved** [comment]
I don't know exactly how you are launching i3 (maybe from .xinitrc?), but if you are using the i3 in your path (ie. the i3 with the version you provided) then you aren't using this changeset. For example my i3 outputs `i3 version 4.16.1-186-gf3fffbae (2020-03-01, branch "shape") © 2009 Michael Stapelberg and contributors`. Notice `branch "shape"` as a key difference. So it could be one of a couple things:

- You mention installing i3-gaps, you might be using airblader/i3-gaps by mistake instead of this repo
- You built the wrong branch (`shape` should be default, but you can double check)
- You built i3, but didn't install it
- Old i3 is still installed and is being preferred for w/e reason

**Comment by dark-eraser** [comment]
The first option might be possible, however i don't think so. I'm gonna try installing the correct branch, thanks. And i followed all the instructions on the wiki so i'm pretty confident i did install i3. And finally it is possible the old i3 is still installed.. I removed it via `apt remove` command however...

Thanks for you help
